/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './../routes/__root'
import { Route as LayoutImport } from './../routes/_layout'
import { Route as LayoutIndexImport } from './../routes/_layout/index'
import { Route as LayoutWorkIndexImport } from './../routes/_layout/work/index'
import { Route as LayoutWorkCollectionSlugImport } from './../routes/_layout/work/$collectionSlug'

// Create/Update Routes

const LayoutRoute = LayoutImport.update({
  id: '/_layout',
  getParentRoute: () => rootRoute,
} as any)

const LayoutIndexRoute = LayoutIndexImport.update({
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutWorkIndexRoute = LayoutWorkIndexImport.update({
  path: '/work/',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutWorkCollectionSlugRoute = LayoutWorkCollectionSlugImport.update({
  path: '/work/$collectionSlug',
  getParentRoute: () => LayoutRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutImport
      parentRoute: typeof rootRoute
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/work/$collectionSlug': {
      id: '/_layout/work/$collectionSlug'
      path: '/work/$collectionSlug'
      fullPath: '/work/$collectionSlug'
      preLoaderRoute: typeof LayoutWorkCollectionSlugImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/work/': {
      id: '/_layout/work/'
      path: '/work'
      fullPath: '/work'
      preLoaderRoute: typeof LayoutWorkIndexImport
      parentRoute: typeof LayoutImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  LayoutRoute: LayoutRoute.addChildren({
    LayoutIndexRoute,
    LayoutWorkCollectionSlugRoute,
    LayoutWorkIndexRoute,
  }),
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_layout"
      ]
    },
    "/_layout": {
      "filePath": "_layout.tsx",
      "children": [
        "/_layout/",
        "/_layout/work/$collectionSlug",
        "/_layout/work/"
      ]
    },
    "/_layout/": {
      "filePath": "_layout/index.tsx",
      "parent": "/_layout"
    },
    "/_layout/work/$collectionSlug": {
      "filePath": "_layout/work/$collectionSlug.tsx",
      "parent": "/_layout"
    },
    "/_layout/work/": {
      "filePath": "_layout/work/index.tsx",
      "parent": "/_layout"
    }
  }
}
ROUTE_MANIFEST_END */
